name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0, 8.1]

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      with:
        version: 9.3
        php_version: ${{ matrix.php }}
